Import('env')
import os
import SCons.Util
import utils




env.CXXFile(target='crawler/Robots_flex.cc', source='crawler/robots.ll')
robots_flex = env.Object('crawler/Robots_flex.cc')

libcommon = env.Library('common', source=env['common_sources'])

env['crawler'] = env.Program('crawler/crawler', SCons.Util.flatten([robots_flex, env['crawler_sources'], libcommon]))


env['local_indexer'] = env.Program('local_indexer/local_indexer', SCons.Util.flatten([
        env['local_indexer_sources'],
        libcommon
    ]))

ut_env = env.Clone()
ut_env.Append(LIBS=['boost_unit_test_framework'])
env['unit_tests'] = ut_env.Program('unit_tests/unit_tests',  SCons.Util.flatten([env['unit_tests_sources'], libcommon]))

#if env['unit_test_sources']:
    #for i in env['unit_test_sources']:
    #    env.Object(i)
