Import('env')
import os
import SCutils
import SCons.Util
import utils



print os.getcwd()

env.CXXFile(target='Robots_flex.cc',source='robots.ll')
robots_flex = env.Object('Robots_flex.cc')

objects = dict()
for i in env['sources']:
    print i
    objects[i] = env.Object(i)


env['crawler'] = env.Program('crawler', SCons.Util.flatten([objects.values(), robots_flex]))


#env['local_indexer'] = env.Program('local_indexer', SCons.Util.flatten([objects['Url, 'local_indexer.cc']))

ut_env = env.Clone()
ut_env.Append(LIBS=['boost_unit_test_framework'])

if env['unit_test_sources']:
    #for i in env['unit_test_sources']:
    #    env.Object(i)
    env['unit_test_exe'] = ut_env.Program('unit_test_exe', env['unit_test_sources'])
