Import('env')
import os
import SCutils
import SCons.Util
import utils



print os.getcwd()

env.CXXFile(target='Robots_flex.cc',source='robots.ll')
robots_flex = env.Object('Robots_flex.cc')


env['crawler'] = env.Program('crawler', SCons.Util.flatten([env['sources'], robots_flex]))

ut_env = env.Clone()
ut_env.Append(LIBS=['boost_unit_test_framework'])

if env['unit_test_sources']:
    #for i in env['unit_test_sources']:
    #    env.Object(i)
    env['unit_test_exe'] = ut_env.Program('unit_test_exe', env['unit_test_sources'])
